import {GvasString} from './Gvas';
import {Industry} from './Railroad';

export enum IndustryType {
    logging_camp = 1,
    sawmill = 2,
    smelter = 3,
    ironworks = 4,
    oil_field = 5,
    refinery = 6,
    coal_mine = 7,
    iron_mine = 8,
    freight_depot = 9,
    firewood_camp = 10,
    engine_house_lightblue = 11,
    engine_house_gold = 12,
    engine_house_red = 13,
    engine_house_brown = 14,
    coaling_tower = 15,
    telegraph_office = 16,
    water_tower_a_red = 20,
    water_tower_a_brown = 21,
    water_tower_a_beige = 22,
    water_tower_a_old = 23,
    water_tower_b_red = 30,
    water_tower_b_brown = 31,
    water_tower_b_beige = 32,
    water_tower_b_old = 33,
    large_engine_house_red = 40,
    large_engine_house_brown = 41,
    large_engine_house_beige = 42,
    large_engine_house_old = 43,
    wood_rick = 44,
}

export const IndustryNames = [
    'CattleFarm',
    'Coalmine',
    'CoalTower',
    'enginehouse_alpine',
    'enginehouse_aspen',
    'enginehouse_barn',
    'enginehouse_princess',
    'engineshed_style1',
    'engineshed_style2',
    'engineshed_style3',
    'engineshed_style4',
    'firewooddepot',
    'freightdepot',
    'GoldDredge',
    'GoldMine',
    'GoldSmelter',
    'IronOreMine',
    'IronWorks',
    'LogCamp',
    'MeatPackingPlant',
    'oilfield',
    'PineValleyEngineHouse',
    'RailExpressAgency',
    'RedMountainDepot',
    'Refinery',
    'Sandhouse',
    'Sawmill',
    'smelter',
    'StampMill',
    'telegraphoffice',
    'watertower_1870_style1',
    'watertower_1870_style2',
    'watertower_1870_style3',
    'watertower_1870_style4',
    'WaterTower_DRGW',
    'watertower_kanaskat_style1',
    'watertower_kanaskat_style2',
    'watertower_kanaskat_style3',
    'watertower_kanaskat_style4',
    'WaterTower_Small',
    'WaterWell',
    'WheatFarm',
    'Woodrick',
] as const satisfies readonly string[];

export const legacyIndustryNames: Record<IndustryType, IndustryName> = {
    [IndustryType.coal_mine]: 'Coalmine',
    [IndustryType.coaling_tower]: 'CoalTower',
    [IndustryType.engine_house_brown]: 'enginehouse_princess',
    [IndustryType.engine_house_gold]: 'enginehouse_aspen',
    [IndustryType.engine_house_lightblue]: 'enginehouse_alpine',
    [IndustryType.engine_house_red]: 'enginehouse_barn',
    [IndustryType.firewood_camp]: 'firewooddepot',
    [IndustryType.freight_depot]: 'freightdepot',
    [IndustryType.iron_mine]: 'IronOreMine',
    [IndustryType.ironworks]: 'IronWorks',
    [IndustryType.large_engine_house_beige]: 'engineshed_style3',
    [IndustryType.large_engine_house_brown]: 'engineshed_style2',
    [IndustryType.large_engine_house_old]: 'engineshed_style4',
    [IndustryType.large_engine_house_red]: 'engineshed_style1',
    [IndustryType.logging_camp]: 'LogCamp',
    [IndustryType.oil_field]: 'oilfield',
    [IndustryType.refinery]: 'Refinery',
    [IndustryType.sawmill]: 'Sawmill',
    [IndustryType.smelter]: 'smelter',
    [IndustryType.telegraph_office]: 'telegraphoffice',
    [IndustryType.water_tower_a_beige]: 'watertower_1870_style3',
    [IndustryType.water_tower_a_brown]: 'watertower_1870_style2',
    [IndustryType.water_tower_a_old]: 'watertower_1870_style4',
    [IndustryType.water_tower_a_red]: 'watertower_1870_style1',
    [IndustryType.water_tower_b_beige]: 'watertower_kanaskat_style3',
    [IndustryType.water_tower_b_brown]: 'watertower_kanaskat_style2',
    [IndustryType.water_tower_b_old]: 'watertower_kanaskat_style4',
    [IndustryType.water_tower_b_red]: 'watertower_kanaskat_style1',
    [IndustryType.wood_rick]: 'Woodrick',
};

const legacyIndustryMap: Record<string, IndustryName> = {
    'coalmine': 'Coalmine',
    'coaltower': 'CoalTower',
    'enginehouse_alpine_blue': 'enginehouse_alpine',
    'enginehouse_aspen_gold': 'enginehouse_aspen',
    'enginehouse_barn_red': 'enginehouse_barn',
    'enginehouse_princes_mineral_brown': 'enginehouse_princess',
    'ironoremine': 'IronOreMine',
    'ironworks': 'IronWorks',
    'logcamp': 'LogCamp',
    'SandHouse': 'Sandhouse',
    'SandHouse_Foundation': 'Sandhouse',
    'sawmill': 'Sawmill',
    'telegraphoffice_foundation': 'telegraphoffice',
    'TelegraphOffice_Foundation': 'telegraphoffice',
    'watertower_1870_style1_foundation': 'watertower_1870_style1',
    'watertower_1870_style2_foundation': 'watertower_1870_style2',
    'watertower_1870_style3_foundation': 'watertower_1870_style3',
    'watertower_1870_style4_foundation': 'watertower_1870_style4',
    'watertower_drgw': 'WaterTower_DRGW',
    'watertower_kanaskat_style1_foundation': 'watertower_kanaskat_style1',
    'watertower_kanaskat_style2_foundation': 'watertower_kanaskat_style2',
    'watertower_small': 'WaterTower_Small',
    'watertower_small_foundation': 'WaterTower_Small',
    'WaterTower_Small_Foundation': 'WaterTower_Small',
    'Waterwell': 'WaterWell',
};

export const isIndustryName = (name: IndustryType | GvasString): name is IndustryName =>
    !!name && (typeof name === 'string') && IndustryNames.includes(name);

export type IndustryName = typeof IndustryNames[number];

export function getIndustryName(industry: Industry): IndustryName | null {
    if (typeof industry.type === 'number') return legacyIndustryNames[industry.type];
    if (isIndustryName(industry.type)) return industry.type;
    if (industry.type === null) return null;
    if (industry.type in legacyIndustryMap) return legacyIndustryMap[industry.type];
    console.warn(`Unrecognized industry type ${industry.type}`);
    return null;
}

export const industryNames: Record<IndustryName, string> = {
    'CattleFarm': 'Cattle Farm',
    'Coalmine': 'Coal Mine',
    'CoalTower': 'Coaling Tower',
    'enginehouse_alpine': 'Engine House (Alpine Blue)',
    'enginehouse_aspen': 'Engine House (Aspen Gold)',
    'enginehouse_barn': 'Engine House (Barn Red)',
    'enginehouse_princess': 'Engine House (Princess Mineral Brown)',
    'engineshed_style1': 'Large Engine House (Red)',
    'engineshed_style2': 'Large Engine House (Brown)',
    'engineshed_style3': 'Large Engine House (Beige)',
    'engineshed_style4': 'Large Engine House (Old)',
    'firewooddepot': 'Firewood Camp',
    'freightdepot': 'Freight Depot',
    'GoldDredge': 'Gold Dredge',
    'GoldMine': 'Gold Mine',
    'GoldSmelter': 'Gold Smelter',
    'IronOreMine': 'Iron Mine',
    'IronWorks': 'Ironworks',
    'LogCamp': 'Logging Camp',
    'MeatPackingPlant': 'Meat Packing Plant',
    'oilfield': 'Oil Field',
    'PineValleyEngineHouse': '4 Stall Roundhouse',
    'RailExpressAgency': 'Rail Express Agency',
    'RedMountainDepot': 'Red Mountain Depot',
    'Refinery': 'Refinery',
    'Sandhouse': 'Sandhouse',
    'Sawmill': 'Sawmill',
    'smelter': 'Smelter',
    'StampMill': 'Stamp Mill',
    'telegraphoffice': 'Telegraph Office',
    'watertower_1870_style1': '1870 Water Tower (Red)',
    'watertower_1870_style2': '1870 Water Tower (Brown)',
    'watertower_1870_style3': '1870 Water Tower (Beige)',
    'watertower_1870_style4': '1870 Water Tower (Old)',
    'WaterTower_DRGW': 'D&RGW Water Tower',
    'watertower_kanaskat_style1': 'Kanaskat Water Tower (Red)',
    'watertower_kanaskat_style2': 'Kanaskat Water Tower (Brown)',
    'watertower_kanaskat_style3': 'Kanaskat Water Tower (Beige)',
    'watertower_kanaskat_style4': 'Kanaskat Water Tower (Old)',
    'WaterTower_Small': 'Small Water Tower',
    'WaterWell': 'Water Well',
    'WheatFarm': 'Wheat Farm',
    'Woodrick': 'Wood Rick',
};

type FourStrings = [string, string, string, string];
const [input2, input3, input4] = ['Unused Input Slot 2', 'Unused Input Slot 3', 'Unused Input Slot 4'];
const [output2, output3, output4] = ['Unused Output Slot 2', 'Unused Output Slot 3', 'Unused Output Slot 4'];

export const industryInputLabels: Partial<Record<IndustryName, FourStrings>> = {
    'CattleFarm': ['Grain', 'Water', 'Straw Bale', input4],
    'Coalmine': ['Beams', 'Rails', input3, input4],
    'CoalTower': ['Coal', input2, input3, input4],
    'firewooddepot': ['Logs', input2, input3, input4],
    'GoldDredge': ['Coal', 'Tool Crates', 'Steel Pipes', input4],
    'GoldMine': ['Coal', 'Beams', 'Rails', 'Tool Crates'],
    'GoldSmelter': ['Refined Gold', 'Coal', input3, input4],
    'IronOreMine': ['Lumber', 'Beams', input3, input4],
    'IronWorks': ['Raw Iron', 'Coal', 'Lumber', input4],
    'MeatPackingPlant': ['Cattle', 'Coal', input2, input4],
    'oilfield': ['Steel Pipes', 'Beams', 'Tool Crates', input4],
    'Refinery': ['Crude Oil', 'Steel Pipes', 'Lumber', input4],
    'Sawmill': ['Logs', input2, input3, input4],
    'smelter': ['Cordwood', 'Iron Ore', input3, input4],
    'StampMill': ['Gold Ore', 'water', 'Coal', 'Cordwood'],
    'WheatFarm': ['Seed Pallet', 'Water', input3, input4],
};

const water: FourStrings = ['Water', output2, output3, output4];
export const industryOutputLabels: Partial<Record<IndustryName, FourStrings>> = {
    'CattleFarm': ['Cattle', 'Cattle', output3, output4],
    'Coalmine': ['Coal', output2, output3, output4],
    'CoalTower': ['Coal', output2, output3, output4],
    'firewooddepot': ['Firewood', 'Firewood', 'Firewood', 'Firewood'],
    'freightdepot': ['Seed Pallet', output2, output3, output4],
    'GoldDredge': ['Gold Ore', output2, output3, output4],
    'GoldMine': ['Gold Ore', output2, output3, output4],
    'GoldSmelter': ['Gold Ingot', output2, output3, output4],
    'IronOreMine': ['Iron Ore', output2, output3, output4],
    'IronWorks': ['Steel Pipes', 'Tool Crates', output3, output4],
    'LogCamp': ['Logs', 'Cordwood', output3, output4],
    'MeatPackingPlant': ['Meat', output2, output3, output4],
    'oilfield': ['Crude Oil', output2, output3, output4],
    'Refinery': ['Oil Barrel', output2, output3, output4],
    'Sandhouse': ['Sand', output2, output3, output4],
    'Sawmill': ['Lumber', 'Beams', output3, output4],
    'smelter': ['Raw Iron', 'Rails', output3, output4],
    'StampMill': ['Refined Gold', output2, output3, output4],
    'telegraphoffice': ['Unknown', output2, output3, output4],
    'watertower_1870_style1': water,
    'watertower_1870_style2': water,
    'watertower_1870_style3': water,
    'watertower_1870_style4': water,
    'WaterTower_DRGW': water,
    'watertower_kanaskat_style1': water,
    'watertower_kanaskat_style2': water,
    'watertower_kanaskat_style3': water,
    'watertower_kanaskat_style4': water,
    'WaterTower_Small': water,
    'WaterWell': water,
    'WheatFarm': ['Grain', 'Straw Bale', output3, output4],
    'Woodrick': ['Firewood', 'Firewood', output3, output4],
};
